### ISSUE TITLE
SOUNDFLOWER-2CH can't able to execute in mac 

### ISSUE THREAD

**Issue by arjungni** [facebookresearch/denoiser#107]
Hi initially i was working once i restart my lap it's not working 

Methods i have done 
created environment -> activate env -> pip install denoiser -> python -m denoiser.live  but now its not working what can i do now

and can i integrate with mac own microphone if possible please help me out

**Comment by adefossez** [comment]
closing this issue and replying there: https://github.com/facebookresearch/denoiser/issues/107
