### ISSUE TITLE
Mistake in the documentation of the dry parameter

### ISSUE THREAD

**Issue by Nithin-Holla** [facebookresearch/denoiser#109]
The documentation mentions that `dry=0` refers to the input signal and `dry=1` refers to the denoised signal. Looking at the code, it seems like it's the other way round. Is that true?

https://github.com/facebookresearch/denoiser/blob/d2db0956d37d16503ad97fb984d589a08b987767/denoiser/enhance.py#L34

**Comment by adefossez** [comment]
thank you for pointing this out, you are totally right, it is the opposite of what is said :)

**Comment by Nithin-Holla** [comment]
@adefossez Thanks! There's one more place where this is referenced which is in the readme: https://github.com/facebookresearch/denoiser#4-denoising
