### ISSUE TITLE
The enhance doesn't  generate denoised file

### ISSUE THREAD

**Issue by peace20162** [facebookresearch/denoiser#117]
I try it on goolgle colab and this is my code: https://colab.research.google.com/drive/1I58upB-kT4wqsqE5W2zdrFPlXUH_U-BG#scrollTo=SBNrIKi7na2v. The audio file length is about 3 secs . I follow the read-me but it doesn't generate anything. please help!

**Comment by peace20162** [comment]
https://colab.research.google.com/drive/1I58upB-kT4wqsqE5W2zdrFPlXUH_U-BG?usp=sharing
sorry i didnt change share setting.

**Comment by adefossez** [comment]
can you show the error you are getting ?

**Comment by peace20162** [comment]
it doesn't show any error but it doesn't have enhanced wav file in enhanced folder.

**Comment by peace20162** [comment]
![Screenshot 2022-04-04 163337](https://user-images.githubusercontent.com/47591499/161516560-443ebfda-6398-46bd-ba47-dd2134fdf785.png)

**Comment by peace20162** [comment]
![Screenshot 2022-04-04 163740](https://user-images.githubusercontent.com/47591499/161517348-d19660d4-5851-4c69-826f-8cda95f4ded3.png)

**Comment by adefossez** [comment]
you need to pass `--noisy_dir /content` (it needs to be a folder, not a file, all files in the folder will be processed).

**Comment by peace20162** [comment]
thank you. it work now.
