### ISSUE TITLE
need pretrained model for 8KHz speech

### ISSUE THREAD

**Issue by JohnHerry** [facebookresearch/denoiser#133]
Is there any pretrained for 8Khz speech? and, are they usable for other languages then the English?

**Comment by adiyoss** [comment]
We do not have a pre-trained 8kHz version, so you would need to train one yourself. 
Regarding languages, although we evaluated it on 16kHz and not 8kHz (I don't think it would make a difference), when we train our model on English only it was also performing pretty good on other languages such as French and Hebrew. 
You can listen to the samples here: https://facebookresearch.github.io/denoiser/

**Comment by JohnHerry** [comment]
Thanks for the help.
