### ISSUE TITLE
master64 same model as reported in the paper?

### ISSUE THREAD

**Issue by pranaymanocha** [facebookresearch/denoiser#14]
Hi,
Thanks for the great repo. I ran the master64 pretrained model (that was trained on VCTK and DNS together) and evaluated it on the VCTK valset. I am getting a PESQ score of 3.019 and STOI of 95.00 (averaged across all 824 files in the valset). This model corresponds to H=64, U=4,S=4, so I looked at the paper and the objective score mentioned there (for the same parameter model) is PESQ=2.94 and STOI =95. Does that look to be correct, or I am doing something wrong here?

One another question I had was regarding access to the non-causal model reported in the paper. Are you guys working to release that soon? Thanks in advance for your response!!

**Comment by adiyoss** [comment]
The numbers you get are fine. The master model was trained on both DNS and Valentini datasets. Its results are not reported in the manuscript. We provide this model so people can use a better performing model for downstream tasks / clean noisy files / etc.
Regarding non-causal training, you can pass `demucs.causal=False` to train a non-causal model.

**Comment by pranaymanocha** [comment]
Thanks for your response! Appreciate it! On my second point, I was more interested in getting access to a pretrained non-causal model. I was curious as to how much better could that model be. The current master64 model is great, but still has a few observable artifacts that I can observe. I was wondering it the non-causal model gets rid of that?

**Comment by adiyoss** [comment]
Ohhh sorry about that...:)
I'll upload the non-causal version soon. The non-causal version was trained on VCTK only, it might be a good idea to train it on a bigger and more challenging set.

**Comment by zhangxingtao** [comment]
where can I find the pretrained models?

**Comment by adiyoss** [comment]
Hi @zhangxingtao ,
You can add `--master64` to your evaluation script and it will automatically download the pre-trained model.
You can do the same with `--dns48` and `--dns64`.

**Comment by adefossez** [comment]
If you want to fine tune from a pre-train model, please see this issue: https://github.com/facebookresearch/denoiser/issues/7
