### ISSUE TITLE
Reduce noise cancellation degree

### ISSUE THREAD

**Issue by dgoryeo** [facebookresearch/denoiser#141]
Is there any way to soften / reduce the amount of denoising? 
Thanks

**Comment by adefossez** [comment]
You can pass ´--dry 0.1´ for instance, this will put back 10% of the original signal + 90% of denoised. You can tune this number to your liking.

**Comment by dgoryeo** [comment]
Hi @adefossez , I'm afraid I'd need to ask for your help again: 

I am trying to pass --dry option in a colab python code as:

import denoiser
options = {"dry":0.1,
                  "device":"cuda",
                  "noisy_dir":path,
                  "model":model} 
denoised = denoiser.enhnace(**options)

But I get error message:  AttributeError: module 'denoiser' has no attribute 'enhnace'. 

Where am I going wrong?

**Comment by balkce** [comment]
There may be a small typo in the line:

`denoised = denoiser.enhnace(**options)`

I think it should be:

`denoised = denoiser.enhance(**options)`

**Comment by dgoryeo** [comment]
Ouch! Embarassing :) 
Thanks a lot for looking int it. 
cheers
