### ISSUE TITLE
Higher sample rate

### ISSUE THREAD

**Issue by LearnedVector** [facebookresearch/denoiser#16]
Hello, thanks for this repo! Is there a pre-trained model for the higher sample rate? something like 44.1khz which is the most common found in audio?

**Comment by adiyoss** [comment]
Hi @LearnedVector,
Sorry, but we do not have a pre-trained model for higher sampling rate. I agree that 44.1khz is very common in audio processing. The main reason we use 16khz is since it is the most common sampling rate in academic speech enhancement benchmarks.

**Comment by LearnedVector** [comment]
Ok got it thanks!
