### ISSUE TITLE
Training on DNS  - training parameters?

### ISSUE THREAD

**Issue by pranaymanocha** [facebookresearch/denoiser#17]
Hi,
I was trying to train the denoiser on DNS, and so I downloaded the dataset from asteroid{https://github.com/mpariente/asteroid/blob/master/egs/dns_challenge}, finished until stage 2 which is preprocessing the dataset. I get around 60K paired files after preprocessing. For training the denoiser, I am unable to run the code at batch_size=128 (which is in 'launch_dns.sh'). With a 12G 1080Ti GPU, I can do atmost batch_size=4, which is taking me around 3 days to do 1 epoch which is a lot, so I was wondering if you guys did any preprocessing on top for DNS?? Thanks!

**Comment by adiyoss** [comment]
Hi @pranaymanocha,
We did not do any input preprocessing. For faster training, we run distributed training on several GPUs, in case you have more than 1 GPU, you can set `ddp=True`.

**Comment by pranaymanocha** [comment]
Thanks for the clarifications!
