### ISSUE TITLE
Distributed training incosstency in train.run(), denoiser/solver.train() and denoiser/solver._run_one_epoch()

### ISSUE THREAD

**Issue by IdoWSC** [facebookresearch/denoiser#21]
Hi,
I noticed that in some cases along these functions sometimes model is used and sometimes dmodel (distributed).

examples:
train.py line 72:
`optimizer = torch.optim.Adam(model.parameters(), lr=args.lr, betas=(0.9, args.beta2))`

denoiser/solver.py in self.train() line 138, 153, 179, 185 :
`self.model.train()`
`self.model.eval()`
`pesq, stoi = evaluate(self.args, self.model, self.tt_loader)`
`enhance(self.args, self.model, self.samples_dir)`

denoiser/solver.py in self._run_one_epoch() line 216:
`estimate = self.dmodel(noisy)`

Is it still consistent with distributed training if the optimizer gets the model.parameters() and not dmodel ones?
Also, the same question regarding the model.train() and eval().

Thanks in advance!!

**Comment by adefossez** [comment]
Yes, the parameters are the same, the distributed model is just a wrapper around the original model but uses the same parameters. In fact if you look at the serialization code for the checkpoints it takes the parameters from the `self.model`.

**Comment by adiyoss** [comment]
Closing this one.
