### ISSUE TITLE
how to compute the time delay or the lookahead time of the causal or uncausal models ?

### ISSUE THREAD

**Issue by YoungJay0612** [facebookresearch/denoiser#22]
In the paper, the lookahead time of the causal Demcus is 37ms and the stride is 16ms，and the process window of H = 64 is 16 ms。 So I don't know how to get these time according to the model or how to compute from the parameters of the source code ?

**Comment by adefossez** [comment]
You can run 
```
python3 -m denoiser.demucs
python3 -m denoiser.demucs --help
```
and it will show you all the numbers. You can pass options like `--depth=4` for instance to test different models.
I will refer you to the code there for the exact details of the computation, in particular the `valid_length` which computes the receptive field of the model, which gives the initial lag.
Note that `H` is not a process window, but a parametrisation of the number of channels in the convolutions.

**Comment by YoungJay0612** [comment]
Thank you so much! I think I have understood your reply!
