### ISSUE TITLE
Recommended architectural parameter changes for higher sample rate 

### ISSUE THREAD

**Issue by LearnedVector** [facebookresearch/denoiser#23]
Any recommendations on architecture changes if we want to train on higher sample rate data?

For example, the number of channels, kernel size, strides, etc from this [line of code](https://github.com/facebookresearch/denoiser/blob/master/denoiser/demucs.py#L76), or even changes to the multiresolution stft loss found [here](https://github.com/facebookresearch/denoiser/blob/master/denoiser/stft_loss.py#L106)? Or maybe even the parameters in Bandmasking found [here](https://github.com/facebookresearch/denoiser/blob/master/denoiser/augment.py#L140).

My intuition is as you have a higher sample rate you want to have larger filter sizes and kernel size to be able to model more frequency bands. Is that a correct assumption? Thanks!

**Comment by adefossez** [comment]
See this issue: https://github.com/facebookresearch/denoiser/issues/19

**Comment by LearnedVector** [comment]
@adefossez thanks! So if I have 44.1khz data, and I use `resample=2`, it'll only upsample by a factor of two before feeding it into the neural net. So you don't recommend any other possible changes?

**Comment by adefossez** [comment]
That's a good starting point :)
