### ISSUE TITLE
kernel_downsample2 & kernel_upsample2 are the same.

### ISSUE THREAD

**Issue by diff7** [facebookresearch/denoiser#25]
These two functions are identical. 
Not sure if it was made with an intention.

https://github.com/facebookresearch/denoiser/blob/84a5c0032d118b619a59b7502a1ffbdddef43fd7/denoiser/resample.py#L34

**Comment by adefossez** [comment]
good catch, it is not made on purpose but it turns out to be true.
Both are an implementation from https://ccrma.stanford.edu/~jos/resample/

**Comment by diff7** [comment]
Got it! I close it as understandable ))
