### ISSUE TITLE
your computer configuration 

### ISSUE THREAD

**Issue by earthjade96** [facebookresearch/denoiser#28]
Hello, may I ask your computer configuration?
And  my video card is 2080ti, Is it applicable?
Thank you very much

**Comment by adefossez** [comment]
You mean for training or just using for evaluation or live denoising ?
For live denoising you can try using your GPU with `--device=cuda`, it should speed up the computation itself, but maybe add too much latency if the memory in the GPU is too slow, we never tested live eval with a GPU.
If that is the case, try passing `-f 2` to `python -m denoiser.live` :)
