### ISSUE TITLE
Is there any way to use multi-threading for `denoiser.enhance`?

### ISSUE THREAD

**Issue by serg06** [facebookresearch/denoiser#35]
This is with `--num_workers=30 --batch_size=30`, and there are 773 wavs in my `noisy_dir`

![image](https://user-images.githubusercontent.com/1350889/103210014-7351ba00-48d2-11eb-85eb-0741a9d89799.png)

My other threads are lonely :(

I love the repo project by the way, insanely cool and effective.

**Comment by adefossez** [comment]
Good point, we did not implement multi threaded separation. I'll try to fix that soon.

**Comment by adefossez** [comment]
Implemented with this commit: https://github.com/facebookresearch/denoiser/commit/be2a78b752a0f7f2bb46624ffe2d1f00676fb903

**Comment by adefossez** [comment]
Closing the issue, let me know if you have trouble with the new implementation but normally it should work :)
