### ISSUE TITLE
Using `--model_path` with pretrained models returns error

### ISSUE THREAD

**Issue by lecidhugo** [facebookresearch/denoiser#36]
Hi,
Inference runs perfectly if I specify the model using --dns48 or --dns64 or --master64. Example:
`python3 -m denoiser.enhance --noisy_dir=../noisy/ --out_dir=../cleaned/ --master64 --sample_rate 16000` will do the job.
However, when I try to specify the path of the pre-trained model explicitly using `--model_path` or `-m` it will break. Example:
`python3 -m denoiser.enhance --noisy_dir=../noisy/ --out_dir=../cleaned/ --model_path /root/.cache/torch/checkpoints/master64-8a5dfb4bb92753dd.th --sample_rate 16000`
will give the following error:
```
INFO:denoiser.pretrained:Loading model from /root/.cache/torch/checkpoints/master64-8a5dfb4bb92753dd.th
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/denoiser/denoiser/enhance.py", line 138, in <module>
    enhance(args, local_out_dir=args.out_dir)
  File "/content/denoiser/denoiser/enhance.py", line 107, in enhance
    model = pretrained.get_model(args).to(args.device)
  File "/content/denoiser/denoiser/pretrained.py", line 60, in get_model
    model = deserialize_model(pkg)
  File "/content/denoiser/denoiser/utils.py", line 35, in deserialize_model
    klass = package['class']
KeyError: 'class'
```
What I am missing here?

Thank you for your awesome project!

**Comment by adefossez** [comment]
That is expected, the option `--model_path` is expected to be used with the checkpoints generated by the training code itself, which is not the same as the one used by PyTorch hub (in particular, the PyTorch hub file contains only the state of the model, but not any metadata on the model like number of layers etc).
What are you trying to do here?

**Comment by lecidhugo** [comment]
I was just trying to test the code locally, i.e. download the pretrained model and then run the code. Is this possible in the current version ?

**Comment by adefossez** [comment]
The `--model_path` argument will only work with a checkpoint from the trainer, so you wont be able to use it in this way.

**Comment by lecidhugo** [comment]
Ok.
Thank you again for your magnificent contribution :+1:
