### ISSUE TITLE
how hydra version？

### ISSUE THREAD

**Issue by GuangyanZhang** [facebookresearch/denoiser#37]
hi，thanks your repo.
I running './train.py ddp=1'
I get the BUg :
Traceback (most recent call last):
  File "./train.py", line 104, in main
    _main(args)
  File "./train.py", line 96, in _main
    start_ddp_workers()
  File "/data/code/denoiser/denoiser/executor.py", line 77, in start_ddp_workers
    log = utils.HydraConfig().hydra.job_logging.handlers.file.filename
AttributeError: 'HydraConfig' object has no attribute 'hydra'

**Comment by adiyoss** [comment]
Hi @GuangyanZhang,
Until we will fix the code to match the latest Hydra version, you can use this Hydra version `hydra_core==0.11.3`.

**Comment by GuangyanZhang** [comment]
ok，thank you! I get the right version,I can do it.

**Comment by GuangyanZhang** [comment]
HI,Where can I download the dev dataset？ I cannot find in this URL:https://datashare.is.ed.ac.uk/handle/10283/2791

**Comment by adiyoss** [comment]
Hi @GuangyanZhang,
We used the data from speakers p286 and p287 for the validation set.

**Comment by adiyoss** [comment]
I'm closing this issue for now. In case you still have troubles feel free to reopen it.
