### ISSUE TITLE
Denosing .wav files using pre-trained model

### ISSUE THREAD

**Issue by archiki** [facebookresearch/denoiser#4]
Hi!
I have a couple of .wav files that I want to denoise using the model you have provided, without any training involved. Could you suggest how that can be done?
Thanks in advance.

**Comment by loretoparisi** [comment]
@archiki it is pretty straightforward!

You do

```
python3 -m denoiser.enhance --noisy_dir=noisy/ --out_dir=cleaned/  --sample_rate 22050
```

where you have to specify the sample rate only if differs 16KHz. The `noisy_dir` contains the noisy files. You will get then

```
.
├── cleaned
│   ├── test_mono_enhanced.wav
│   └── test_mono_noisy.wav
└── noisy
    └── test_mono.wav

2 directories, 3 files
```

**NOTE**.  Currently you need mono input signal, so be sure to convert to mono your wav file:

```
ffmpeg -i noisy/test.wav -ac 1 noisy/test_mono.wav
```

**Comment by archiki** [comment]
Thanks a lot @loretoparisi!

**Comment by youssefavx** [comment]
@loretoparisi  Hey! Thanks so much for providing instructions. In trying this command, I'm getting this error which I'm not sure how to solve:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/denoiser/enhance.py", line 15, in <module>
    import torchaudio
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/torchaudio/__init__.py", line 1, in <module>
    from . import extension
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/torchaudio/extension/__init__.py", line 5, in <module>
    _init_extension()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/torchaudio/extension/extension.py", line 12, in _init_extension
    _init_script_module(ext)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/torchaudio/extension/extension.py", line 19, in _init_script_module
    torch.classes.load_library(path)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/torch/_classes.py", line 46, in load_library
    torch.ops.load_library(path)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/torch/_ops.py", line 105, in load_library
    ctypes.CDLL(path)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/torchaudio/_torchaudio.so, 6): Symbol not found: __ZN2at5emptyEN3c108ArrayRefIxEERKNS0_13TensorOptionsENS0_8optionalINS0_12MemoryFormatEEE
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/torchaudio/_torchaudio.so
  Expected in: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/torch/lib/libtorch_cpu.dylib
 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/torchaudio/_torchaudio.so
```

Running on MacOS Mojave 10.14. 

Would love any help whatsoever!

**Comment by youssefavx** [comment]
Never mind! Sorry I upgraded torchaudio and it automatically tried to upgrade torch, after upgrading, I ran the command again with --master64 and it's downloading the model now.

**Comment by youssefavx** [comment]
Okay, I'm now getting this error:

```
Floating point exception: 8
```

**Comment by youssefavx** [comment]
I should note I'm trying this on an hour and 10 minute file. I might try smaller files too.

**Comment by youssefavx** [comment]
Okay I just tried restarting and then running a long file but it was too slow, so then I tried with a 20 second sample and it worked! The only trouble is the output doesn't have any speech (or rather has very very short glitches of speech). I then sey --dry to 0.1 and I'm not sure if I'm getting a total reduction in the volume or an actual reduction in the noise.

**Comment by youssefavx** [comment]
Am I missing something here? Is this supposed to work on completely new files with new kinds of noise or should one train it with one's own dataset that closely matches the noise of the input file? I'm working with noise that isn't something one would face in a public setting, more like tape noise.

**Comment by youssefavx** [comment]
How interesting... when I dropped the Khz from 44100 (converted the audio file) to 22050 Khz, I immediately got better results. I'll try dropping further.

**Comment by loretoparisi** [comment]
> How interesting... when I dropped the Khz from 44100 (converted the audio file) to 22050 Khz, I immediately got better results. I'll try dropping further.

Definitively use 22kHz

```bash
python3 -m denoiser.enhance --noisy_dir=noisy/ --out_dir=cleaned/  --sample_rate 22050
```

**Comment by youssefavx** [comment]
It seems I'm getting better less glitchy results when dropped to 16khz, is there a reason for that or might I be doing something wrong?

**Comment by adiyoss** [comment]
Hi,
@youssefavx, the model was trained on audio files sampled at 16khz, so it should work best using that sample rate. 
I can't say much about the performance of our model using higher sampling rates. 
Regarding slow runtime, if you do not need an online denoising, you can set the `streaming` flag in `enhance.py` script to false. This will convert to batch evaluation, which will be faster and provide slightly better denoising performance.

**Comment by youssefavx** [comment]
Thanks @adiyoss ! I think I'll try fine tuning. I tried doing this:

`python3 -m denoiser.enhance --noisy_dir=noisy/ --out_dir=clean/ --streaming false  --sample_rate 16000`

But I'm getting this error:

```
usage: denoiser.enhance [-h] [-m MODEL_PATH | --dns48 | --dns64 | --master64]
                        [--device DEVICE] [--dry DRY]
                        [--sample_rate SAMPLE_RATE]
                        [--num_workers NUM_WORKERS] [--streaming]
                        [--out_dir OUT_DIR] [--batch_size BATCH_SIZE] [-v]
                        [--noisy_dir NOISY_DIR | --noisy_json NOISY_JSON]
denoiser.enhance: error: unrecognized arguments: false
```

I think I misunderstood what you meant though.

**Comment by youssefavx** [comment]
Also, I'm curious what bit depth was used to train the model?

**Comment by adiyoss** [comment]
You can not set `--streaming false`. If you do not include `--streaming` in your python command than it will use the batch mode.

**Comment by youssefavx** [comment]
Ah! makes sense, thank you so much for all the help so far! Most people I meet aren't this open to beginners.
