### ISSUE TITLE
Processing error with custom dataset

### ISSUE THREAD

**Issue by Skeef79** [facebookresearch/denoiser#43]
I am training my model on custom dataset, when doing first evaluation this happens:
![image](https://user-images.githubusercontent.com/35370908/105667715-a309d700-5efd-11eb-937c-eae6874186bb.png)
What "Processing Error" is? How to fix it?

**Comment by adefossez** [comment]
Can you try again with `--eval_workers=0` ? (or pass `workers=0` to `evaluate` if you are calling it directly).

**Comment by adefossez** [comment]
The Processing error is coming from the `PESQ` library. We only noticed it happened if some examples were very badly separated by the model. Sadly the PESQ library sometimes exit the entire program if it finds an issue, without giving much information. If you pass `pesq=0` then the problem should go away (but you won't have the PESQ metric). You can try to then evaluate the model only once it is fulled trained.
