### ISSUE TITLE
Why is bandmask applied on both input (noisy) and target (clean)??

### ISSUE THREAD

**Issue by LearnedVector** [facebookresearch/denoiser#45]
Hi thanks for the repo! I have a question. Why is bandmask applied on both input (noisy) and target (clean)?? would it make sense to only apply bandmask on the input data and let the model reconstruct the missing frequencies? Sorry if this questions is obvious and i just lack some fundamental understanding! Would greatly appreciate any insight on this.

**Comment by adefossez** [comment]
Filling bits that are not in the input audio would be a bit more than just denoising. If we apply it to both the noisy and clean, all we are doing is generating a new denoising task, where some frequencies are missing in both the input and output. If we are only removing in the noisy, then we are asking the model to make up some content, which, while interesting, is not strictly speaking denoising.

**Comment by LearnedVector** [comment]
ok thanks this makes sense!
