### ISSUE TITLE
What parameters to set to train a deeper network?

### ISSUE THREAD

**Issue by youssefavx** [facebookresearch/denoiser#46]
Hey guys thanks for all the help so far! 

I’m curious if I wanted to train from scratch a deeper network, what parameters do I need to change in the yaml config file?

When I fine tuned dns48 and dns64 on 44.1kHz it worked great but I felt that for some reason the higher res frequencies weren’t really as present in the denoiser recording as in the original recording and I’m wondering if that had something to do with the size of the network

Ideally I’d want it to even ‘fill in’ a bit where the higher res frequencies aren’t really audible.

Although maybe this is getting into changing the actual architecture.

**Comment by adefossez** [comment]
you could try to increase the depth of the network to 6, not sure it will help though.

**Comment by youssefavx** [comment]
Thank you! I will give it a shot but am curious if you have any tips on what might help for a higher-res sound.

**Comment by adefossez** [comment]
You can have a look at this issue where the topic was discussed: https://github.com/facebookresearch/denoiser/issues/19

**Comment by youssefavx** [comment]
Ah I see, yeah I guess I will also try setting demucs.hidden to 64 or maybe even higher when training on 44.1kHz.

**Comment by youssefavx** [comment]
Just to report back to those interested in this:

On a subjective level, I feel like I do hear more high frequencies but not too much. I will try to be a bit more rigorous and look at the spectrograms + EQ. 

However, I'm not sure if this is due to training 44kHz from scratch (I suspect this is the reason), or because I had my `demucs.hidden` set to `96` and `depth` set to `6` instead of `5` (I doubt this had any effect). 

I will do another test by training from scratch with `demucs.hidden` set to `64` and compare.

**Comment by sarahspak** [comment]
@youssefavx I was also interested in developing a version of the denoiser that was trained on 44.1kHz - did setting demucs.hidden to 64 improve performance?
