### ISSUE TITLE
RuntimeError: Given groups=1, weight of size [48, 1, 8], expected input[1, 2, 114721108] to have 1 channels, but got 2 channels instead

### ISSUE THREAD

**Issue by mennatallah644** [facebookresearch/denoiser#50]
![error2](https://user-images.githubusercontent.com/32370077/107640848-8a2e4f00-6c7b-11eb-9592-c0915e6a1358.PNG)

**Comment by adefossez** [comment]
You cannot use denoiser with stereo inputs. You must downmix it to mono first, for instance
```
fffmpeg -i input.wav -ac 1 -ar 16000 output.wav
```

**Comment by mennatallah644** [comment]
@adefossez Thanks
