### ISSUE TITLE
The script to generate the egs/ files

### ISSUE THREAD

**Issue by ntyoshi** [facebookresearch/denoiser#52]
Hi, Thanks for this great work.
I'm trying to reproduce your paper results and ran script you gave us at README.md in order to generate the egs/ files of Valentini and DNS but json files weren't saved.
Please check my questions below.

1. I took a look at denoiser/audio.py and I wonder if `json.dump(meta, sys.stdout, indent=4)` at the bottom line worked in your environment.
When I changed it to `json.dump(meta, sys.argv[2], indent=4)`, the script looked work well in the case of valentini. 
2. When I tried dns script after I cloned DNS-challenge (interspeech2020/master), the part of `$testset/synthetic/reverb/noisy` seemed to be weird because there is no directory. I guess it means `$testset/synthetic/with_reverb/noisy` but is it true? Or should I change the branch of the DNS-challenge repository?

Thank you!

**Comment by adefossez** [comment]
Hey @ntyoshi 

For 1.: you need to redirect the output of the script: for instance `python -m denoiser.audio NOISY_PATH > OUT_PATH/noisy.json`, otherwise it will just print the list to stdout.

2. I'll fix the readme, the path is indeed `with_reverb/noisy`.

Let me know if you have other issues :)

**Comment by ntyoshi** [comment]
For 1., I think the script `python -m denoiser.audio $noisy_train egs/val/tr/noisy.json` should be changed to `python -m denoiser.audio $noisy_train > egs/val/tr/noisy.json` (the other lines should be done as well).

**Comment by adefossez** [comment]
Correct :) Sorry I missed that.

**Comment by ntyoshi** [comment]
Thank you for confirmation!
It looks working well on my environment as well.

**Comment by adefossez** [comment]
I'll close the issue now, please reopen if you still encounter issues :)

**Comment by ntyoshi** [comment]
@adefossez 
Hi, let me ask about Valentini noisy.json here.
The script you gave us generate the noisy test set as `egs/val/tt/noisy.json`.
But at 5th line conf/dset/valentini.yaml, the default value of `noisy_json` is `egs/valentini/ts/noisy.json`.
Are they different?
