### ISSUE TITLE
hubconf models update

### ISSUE THREAD

**Issue by SolomidHero** [facebookresearch/denoiser#55]
Hi! Thank you for your work! Can you add existing model to `hubconf.py`? Seems that there are some mistakes in current models' names:
https://github.com/facebookresearch/denoiser/blob/70833815e140cc8b7d060fb127e1ebfd48718a51/hubconf.py#L9

Thank you!

**Comment by adefossez** [comment]
is it working now?

**Comment by SolomidHero** [comment]
Yes! Thank you for your quick fix!
