### ISSUE TITLE
Valentini testset

### ISSUE THREAD

**Issue by ntyoshi** [facebookresearch/denoiser#61]
Hi, let me ask about Valentini noisy.json here.
The script you gave us generate the noisy test set as egs/val/tt/noisy.json.
But at 5th line conf/dset/valentini.yaml, the default value of noisy_json is egs/valentini/ts/noisy.json.
Are they different?

**Comment by adiyoss** [comment]
Hi @ntyoshi, 
Sorry for being unclear with this. The parameter `noisy_json` inside the `valentini.yaml` file is used for separate a sample set of file after each evaluation. You can leave it empty of you can create a small sample set by yourself.

**Comment by ntyoshi** [comment]
Sure! Thank you!
