### ISSUE TITLE
pip install defaults to torch version 1.8

### ISSUE THREAD

**Issue by amartya-dev** [facebookresearch/denoiser#65]
`pip install denoiser` defaults to installing `torch-1.8.0` which is not supported by the project, since the file `denoiser/audio.py` uses `torchaudio.info` which only returns a `AudioMeta` object now and that throws an error.

**Comment by adefossez** [comment]
should be fixed now, thanks for raising the issue !

**Comment by amartya-dev** [comment]
Yes, I think now it is compatible with version 1.8 itself, that is great
