### ISSUE TITLE
tradeoffs to think about when training this model on 48khz data?

### ISSUE THREAD

**Issue by sarahspak** [facebookresearch/denoiser#80]
Hello, 

I've tried this model out and am really impressed with its performance - thank you for sharing this! 

However, the output sounds lofi (probably because of the 16khz sample rate), so I've been looking into retraining this model on 48khz sample rate audio.

I saw that the Valentini dataset used was initially 48khz and downsampled to 16khz for model training - why was this choice made? Was it because training on 48khz audio would take significantly longer? 

 
https://github.com/facebookresearch/denoiser/issues/74

**Comment by adefossez** [comment]
16kHz is the standard frequency for comparing models for denoising. In fact, some metrics like PESQ are not even well defined or implemented above 16kHz as far as I know.
You would need to retrain on the DNS dataset to get a model usable in real life though: https://github.com/facebookresearch/denoiser/issues/71
The valentini dataset doesn't have enough diversity in noises for real life uses, and is mostly a benchmark for research.

**Comment by 008karan** [comment]
I want to use denoiser for 8khz audio. And after testing its not working fine. reason being its trained on 16khz data. If I train it on 8khz from scratch would that work or finetune it on 8khz data would be better? @adefossez

**Comment by adefossez** [comment]
For an 8kHz model, it should be good enough to first upsample the audio (if you have ffmpeg installed, `ffmpeg -i original_wav.wav -ac 1 -ar 16000 output_wav.wav`) and I would expect the model to work okay even if some frequencies are missing.
