### ISSUE TITLE
Theoretical and technical details

### ISSUE THREAD

**Issue by olmatz** [facebookresearch/denoiser#85]
Hi,

First of all, I would like to thanks @adefossez  for the amazing work done on demucs and denoiser.

I have a couple of theoretical/technical questions:
- According to issues #44 and #82, I have compute the size of one frame regarding the architecture in the paper (K=8, S=4, L=5 and U=4) and I found $T_1$ = 2388 (37.31ms for sr = 16 000x4). However, to convert it into duration, it will depends of the sampling rate or more precisely to the up-sampling. So if we turn off the up-sampling, the frame duration will be quite high (149ms). Am I right or did I miss something?

- Is the "stride" related to the stride operation on an audio sample in the case of the sample are bigger than the "segment"? https://github.com/facebookresearch/denoiser/blob/a400897fc58619a8a9cea967d1e28a6329f5dc50/conf/config.yaml#L8-L9

- How the length (time/sequence dimension) of the LSTM is defined? Is it defined by the maximum length of audio or by the segment? i.e. if we set "segment" to _n_ seconds, then we can compute the time step LSTM length by: _n_/frame_duration?

- If this is the case, how is it possible to use denoiser model in inference on audio bigger than the duration set via "segment"? I think I missed something in the paper but I cannot figure out what.

Any help will be very appreciated.

Have a nice day.

**Comment by adefossez** [comment]
Hey @olmatz
@adiyoss is also to be credited for the denoiser project :)

If you turn off upsampling then yes, frame size will be 4 times bigger. This is actually one usefulness of the resampling: to change the framesize without touching the overall architecture.

the stride parameter is used to define how we pass over an audio file, indeed when it is longer than segment. For instance if segment is 4 seconds, and we have a 6 seconds file, with a stride of 1 we would have 3 training example: [0, 4], [1, 5], [2, 6].

Length of the lstm is defined by the length of the input audio. for the batch implementation, this is just the length of what comes out of the convolutional encoder. For the streaming one, audio is automatically cut into small chunks that each corresponds to a single LSTM step.

You can use on audio bigger than what defined on segment. In fact, I use regularly the streaming implementation for calls, which can last for hours, without reseting at any point the model. The only limitation is if audio volume varies a lot within a very big file, then you might want to chunk it first.
