### ISSUE TITLE
where do I download pretrained models?

### ISSUE THREAD

**Issue by NewEricWang** [facebookresearch/denoiser#86]
I can't find the pretrained models, such as "dns48". Where are they?

**Comment by adefossez** [comment]
they are automatically downloaded through pytorch hub when you pass the appriopriate flag (e.g. `--dns48`). The model dumps themselves will be stored in `~/.cache/torch/hub` on OSX and Linux.

**Comment by NewEricWang** [comment]
Thanks a lot!

**Comment by muhammad-usama-aleem** [comment]
@adefossez is there any way by which I can run model without internet on the first try. Like downloading the model before hand in the same directory as my main file or load the checkpoints locally.
