### ISSUE TITLE
Enhance pre-recorded audio files from script

### ISSUE THREAD

**Issue by jianupetrut** [facebookresearch/denoiser#96]
Hello,

Relating to issue #64  - is there any way to use this within a python script without calling subprocess.run ?
For example, something like

```
import denoiser

...some code...
denoiser.enhance(noisy_dir=PATH,out_dir=PATH2)
...more code...

```

Thanks in advance

**Comment by adefossez** [comment]
Hello @jianupetrut, at the moment there is no easy way to do so, although you could make one easily by taking inspiration from the [enhance.py file](https://github.com/facebookresearch/denoiser/blob/main/denoiser/enhance.py).

**Comment by jianupetrut** [comment]
Understood. Thank you for your reply!
