### ISSUE TITLE
DNS evaluation metric

### ISSUE THREAD

**Issue by IdoWSC** [facebookresearch/denoiser#97]
Hi,
In the article it is stated that the DNS measure is "overall MOS".
can you please describe how this measure is calculated?

**Comment by adiyoss** [comment]
Hi @IdoWSC,
Overall, we conducted three subjective tests: 1) BAK - in which raters were asked to evaluate the level intrusiveness of the background noise in the recording in a scale of 1-5; 2) SIG - in which rates were asked to evaluate the level of distortion in a given recording in a scale of 1-5; and 3) overall - in which raters were asked to evaluate the overall quality of the recordings (considering all of the above) in a scale of 1-5. 
So overall MOS is the third one :).

**Comment by IdoWSC** [comment]
Thanks for the prompt reply @adiyoss
