### ISSUE TITLE
denoiser.live can't connect to sink interface

### ISSUE THREAD

**Issue by codeuntilcold** [facebookresearch/denoiser#98]
Hi, I'm trying to get `denoiser.live` running and run in a bit of a blunder.

In the README, it is advised that we create a sink (in PulseAudio's terminology) named `denoiser` and connect our video conferencing app's mic to the _Monitor of Null Output_ interface. 

After a bit of research, I found that this _Monitor_ is a loopback of the `denoiser` sink, meaning that any audio entering the sink will also appear at the monitor.

So I figured that `denoiser.live` should `--out` to the `denoiser` sink, right? Because then the clean audio will land on the `denoiser` sink and appear in the monitor, hence become the input audio of our video conferencing app!

But in my case, `denoiser.live` can only `--out` to sources (again using PulseAudio's terminology, sources are the mic or the monitor), instead of sinks. Can anyone explain why is this happening? Any response would be a tremendous help.

**Comment by adefossez** [comment]
This is correct, but `denoiser.live` cannot directly output to the `denoiser` sink because the library `sounddevice` doesn't actually list the pulseaudio interfaces, which are higher level than the ALSA one. So you need to select any out interface at first and then change it manually inside `pavucontrol`. let me know if that works.

related: https://github.com/facebookresearch/denoiser/issues/95

**Comment by codeuntilcold** [comment]
Yeah I tried doing that by choosing the default interface, but then the terminal kept saying `ALSA lib pcm.c:8526:(snd_pcm_recover) underrun occurred` which I guessed was because there was nothing for the programm to process. And then the Python process in `pavucontrol` got super glitchy too, so I couldn't change the interface to those of PulseAudio.

But from what I've seen, it seems that `pavucontrol` can only display ALSA interfaces.

![image](https://user-images.githubusercontent.com/55499704/140932002-6120e71f-4af8-4a43-9b64-2a810cdd9b29.png)

**Comment by adefossez** [comment]
okay, I had the same issue in my Linux VM but I assumed this was because I was running from a VM.
An alternative way would be try to use `snd-aloop`  from ALSA, but I wasn't able to configure it to offer the proper sample rate (e.g. 16kHz, not 44.1kHz).

**Comment by codeuntilcold** [comment]
Linux is hard man 😂 

I thought I had it all sorted out by changing my mic's sample rate to 16kHz and setting Playback on _denoiser_ and Recording from _mic_ in `pavucontrol`, but nope, the whole thing is still very much glitchy and nothing gets denoised. 

Might try `snd-aloop` or actually dual-booting Linux to tackle this problem. I'll tell u when there's any progress.

Thank you so much for helping me!
